'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import type { AdminTab, Mode, Product, School, Student, StudentTab, Voucher } from '@/lib/types';

const fmt = (sec:number) => `${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;
const uid = () => Math.random().toString(36).slice(2,10);
const defaultProducts: Product[] = [
  { id:'p1', name:'초코 우유', points:700, image:'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=500&q=80', active:true },
  { id:'p2', name:'삼각김밥', points:1100, image:'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=500&q=80', active:true },
  { id:'p3', name:'샌드위치', points:1500, image:'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=500&q=80', active:true }
];
const defaultStudents: Student[] = [
  { id:'s1', name:'김민준', grade:2, classNo:3, number:12, points:2310 },
  { id:'s2', name:'이서연', grade:1, classNo:5, number:7, points:1740 },
  { id:'s3', name:'박지후', grade:3, classNo:1, number:18, points:890 }
];

export default function Page(){
  const [mode,setMode]=useState<Mode>('student');
  const [studentTab,setStudentTab]=useState<StudentTab>('home');
  const [adminTab,setAdminTab]=useState<AdminTab>('overview');
  const [signedUp,setSignedUp]=useState(true);
  const [points,setPoints]=useState(2310);
  const [monthlyMinutes,setMonthlyMinutes]=useState(1260);
  const [rewardPer30,setRewardPer30]=useState(70);
  const [growthTarget,setGrowthTarget]=useState(15);
  const [rewardProductId,setRewardProductId]=useState('p1');
  const [products,setProducts]=useState<Product[]>(defaultProducts);
  const [wallet,setWallet]=useState<Voucher[]>([]);
  const [students,setStudents]=useState<Student[]>(defaultStudents);
  const [schools,setSchools]=useState<School[]>([{id:'sch1',name:'스테디 고등학교',code:'STEADY2026'}]);

  useEffect(()=>{
    const raw=localStorage.getItem('steady-point-state');
    if(raw){ try { const s=JSON.parse(raw); Object.entries(s).forEach(()=>{}); setPoints(s.points??2310); setMonthlyMinutes(s.monthlyMinutes??1260); setRewardPer30(s.rewardPer30??70); setGrowthTarget(s.growthTarget??15); setProducts(s.products??defaultProducts); setWallet(s.wallet??[]); setStudents(s.students??defaultStudents); setSchools(s.schools??schools); setSignedUp(s.signedUp??true); } catch{} }
  },[]);
  useEffect(()=>{ localStorage.setItem('steady-point-state',JSON.stringify({points,monthlyMinutes,rewardPer30,growthTarget,products,wallet,students,schools,signedUp})); },[points,monthlyMinutes,rewardPer30,growthTarget,products,wallet,students,schools,signedUp]);

  const purchase=(p:Product)=>{
    if(points<p.points) return alert('포인트가 부족합니다.');
    if(!confirm(`${p.name}을(를) ${p.points.toLocaleString()}P에 구매할까요?`)) return;
    setPoints(v=>v-p.points);
    setWallet(v=>[{id:uid(),productId:p.id,productName:p.name,image:p.image,purchasedAt:Date.now(),used:false},...v]);
    alert('구매가 완료되어 내 지갑에 보관되었습니다.');
  };

  return <main className="min-h-screen p-3 md:p-6">
    <div className="mx-auto max-w-7xl">
      <header className="mb-5 flex flex-col gap-3 rounded-[24px] border border-white/80 bg-white/90 p-3 shadow-sm backdrop-blur md:flex-row md:items-center md:justify-between">
        <div className="flex items-center gap-3 px-2"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-600 text-lg font-black text-white">S</div><div><h1 className="font-bold tracking-tight">steady point</h1><p className="text-xs text-slate-500">Study steadily. Grow visibly.</p></div></div>
        <div className="flex rounded-2xl bg-slate-100 p-1 text-sm font-semibold">
          <button className={`flex-1 rounded-xl px-4 py-2 ${mode==='student'?'bg-white text-blue-600 shadow-sm':'text-slate-500'}`} onClick={()=>setMode('student')}>학생 모드</button>
          <button className={`flex-1 rounded-xl px-4 py-2 ${mode==='admin'?'bg-white text-blue-600 shadow-sm':'text-slate-500'}`} onClick={()=>setMode('admin')}>관리자 모드</button>
        </div>
      </header>
      {mode==='student' ? (signedUp ? <StudentApp tab={studentTab} setTab={setStudentTab} points={points} monthlyMinutes={monthlyMinutes} rewardPer30={rewardPer30} setPoints={setPoints} setMonthlyMinutes={setMonthlyMinutes} products={products} wallet={wallet} setWallet={setWallet} purchase={purchase} growthTarget={growthTarget}/> : <Signup schools={schools} onDone={()=>setSignedUp(true)}/>) : <AdminApp tab={adminTab} setTab={setAdminTab} products={products} setProducts={setProducts} rewardPer30={rewardPer30} setRewardPer30={setRewardPer30} growthTarget={growthTarget} setGrowthTarget={setGrowthTarget} rewardProductId={rewardProductId} setRewardProductId={setRewardProductId} schools={schools} setSchools={setSchools} students={students} setStudents={setStudents} wallet={wallet} setWallet={setWallet}/>} 
    </div>
  </main>
}

function Signup({schools,onDone}:{schools:School[];onDone:()=>void}){
  const [step,setStep]=useState(1); const [code,setCode]=useState(''); const [ok,setOk]=useState(false);
  const [form,setForm]=useState({id:'',pw:'',grade:'1',classNo:'1',number:'1',privacy:false,device:false});
  const verify=()=>{ const found=schools.some(s=>s.code.trim().toUpperCase()===code.trim().toUpperCase()); setOk(found); if(found)setStep(2); else alert('유효하지 않은 학교 코드입니다.'); };
  const submit=()=>{ if(!form.id||!form.pw||!form.privacy||!form.device) return alert('필수 정보와 동의 항목을 모두 확인해 주세요.'); onDone(); };
  return <div className="mx-auto max-w-xl card p-7 md:p-10"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-600">STUDENT SIGN UP</span><h2 className="mt-4 text-3xl font-bold">학교 인증 후 가입하기</h2><p className="mt-2 text-sm text-slate-500">모든 사용자는 만 15세 이상으로 간주됩니다.</p>
    <div className="mt-8 flex gap-2"><div className={`h-1.5 flex-1 rounded-full ${step>=1?'bg-blue-600':'bg-slate-200'}`}/><div className={`h-1.5 flex-1 rounded-full ${step>=2?'bg-blue-600':'bg-slate-200'}`}/></div>
    {step===1?<div className="mt-8"><label className="label">학교 코드</label><input className="input" value={code} onChange={e=>setCode(e.target.value)} placeholder="예: STEADY2026"/><button onClick={verify} className="btn-primary mt-4 w-full">학교 코드 인증</button></div>:
    <div className="mt-8 space-y-4"><div><label className="label">개인 아이디</label><input className="input" value={form.id} onChange={e=>setForm({...form,id:e.target.value})}/></div><div><label className="label">비밀번호</label><input type="password" className="input" value={form.pw} onChange={e=>setForm({...form,pw:e.target.value})}/></div><div className="grid grid-cols-3 gap-3">{[['학년','grade'],['반','classNo'],['번호','number']].map(([l,k])=><div key={k}><label className="label">{l}</label><input type="number" min="1" className="input" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}</div>
      <label className="flex items-start gap-3 rounded-2xl bg-slate-50 p-4 text-sm"><input type="checkbox" className="mt-1" checked={form.privacy} onChange={e=>setForm({...form,privacy:e.target.checked})}/><span><b>개인정보 수집 및 이용 동의</b><br/><span className="text-xs text-slate-500">학교 인증, 학습 기록, 보상 제공을 위한 필수 동의</span></span></label>
      <label className="flex items-start gap-3 rounded-2xl bg-slate-50 p-4 text-sm"><input type="checkbox" className="mt-1" checked={form.device} onChange={e=>setForm({...form,device:e.target.checked})}/><span><b>기기 접근 권한 허가</b><br/><span className="text-xs text-slate-500">화면 이탈 감지 및 부정 사용 방지를 위한 필수 권한</span></span></label>
      <button onClick={submit} className="btn-primary w-full">가입 완료</button></div>}
    {ok&&<p className="mt-4 text-center text-xs font-semibold text-emerald-600">학교 코드 인증이 완료되었습니다.</p>}
  </div>
}

function StudentApp(props:any){
  const nav:[StudentTab,string][]=[['home','홈'],['timer','타이머'],['store','스토어'],['wallet','내 지갑'],['stats','통계']];
  return <div className="grid gap-5 md:grid-cols-[210px_1fr]"><aside className="card flex gap-2 overflow-x-auto p-3 md:block md:space-y-2 md:p-4">{nav.map(([id,label])=><button key={id} onClick={()=>props.setTab(id)} className={`min-w-fit rounded-2xl px-4 py-3 text-left text-sm font-semibold md:w-full ${props.tab===id?'bg-blue-600 text-white':'text-slate-500 hover:bg-slate-100'}`}>{label}</button>)}</aside><section>{props.tab==='home'&&<StudentHome {...props}/>} {props.tab==='timer'&&<StudyTimer {...props}/>} {props.tab==='store'&&<Store {...props}/>} {props.tab==='wallet'&&<Wallet {...props}/>} {props.tab==='stats'&&<Stats {...props}/>}</section></div>
}
function StudentHome({points,monthlyMinutes,setTab}:any){ const progress=Math.min(100,Math.round(monthlyMinutes/1800*100)); return <div className="space-y-5"><div className="card overflow-hidden p-7 md:p-10"><p className="text-sm font-semibold text-blue-600">안녕하세요, 김민준 학생</p><h2 className="mt-2 text-3xl font-bold md:text-4xl">오늘도 조금씩, 꾸준하게.</h2><p className="mt-3 text-slate-500">완료한 공부 시간만큼 포인트가 바로 쌓입니다.</p><button className="btn-primary mt-7" onClick={()=>setTab('timer')}>공부 시작하기</button></div><div className="grid gap-5 md:grid-cols-2"><div className="card p-6"><p className="text-sm text-slate-500">현재 보유 포인트</p><p className="mt-3 text-4xl font-bold">{points.toLocaleString()}<span className="ml-1 text-lg text-blue-600">P</span></p><p className="mt-3 text-xs text-slate-400">매점 상품으로 교환할 수 있어요.</p></div><div className="card flex items-center gap-6 p-6"><div className="grid h-28 w-28 place-items-center rounded-full" style={{background:`conic-gradient(#2563eb ${progress}%,#e8edf4 0)`}}><div className="grid h-20 w-20 place-items-center rounded-full bg-white text-center"><b>{progress}%</b><span className="text-[10px] text-slate-400">월 목표</span></div></div><div><p className="text-sm text-slate-500">이번 달 누적</p><p className="mt-2 text-3xl font-bold">{Math.floor(monthlyMinutes/60)}시간 {monthlyMinutes%60}분</p><p className="mt-2 text-xs text-emerald-600">지난달보다 18% 성장 중</p></div></div></div></div> }

function StudyTimer({rewardPer30,setPoints,setMonthlyMinutes}:any){
  const [minutes,setMinutes]=useState(60); const [remaining,setRemaining]=useState(0); const [running,setRunning]=useState(false); const [hiddenLeft,setHiddenLeft]=useState<number|null>(null); const tick=useRef<any>(null); const hiddenTimer=useRef<any>(null);
  const invalidate=()=>{setRunning(false);setRemaining(0);setHiddenLeft(null);clearInterval(tick.current);clearInterval(hiddenTimer.current);alert('화면을 5초 이상 벗어나 타이머가 무효 처리되었습니다. 포인트는 지급되지 않습니다.');};
  useEffect(()=>{ if(running){tick.current=setInterval(()=>setRemaining((v:number)=>{if(v<=1){clearInterval(tick.current);setRunning(false);setPoints((p:number)=>p+minutes/30*rewardPer30);setMonthlyMinutes((m:number)=>m+minutes);setTimeout(()=>alert(`${minutes}분 공부 완료! ${(minutes/30*rewardPer30).toLocaleString()}P가 적립되었습니다.`),20);return 0;}return v-1;}),1000);} return()=>clearInterval(tick.current); },[running]);
  useEffect(()=>{ const onVis=()=>{ if(!running)return; if(document.hidden){let left=5;setHiddenLeft(left);hiddenTimer.current=setInterval(()=>{left-=1;setHiddenLeft(left);if(left<=0)invalidate();},1000);}else{clearInterval(hiddenTimer.current);setHiddenLeft(null);} }; document.addEventListener('visibilitychange',onVis); return()=>document.removeEventListener('visibilitychange',onVis); },[running]);
  const start=()=>{if(!confirm('타이머 작동 중 앱 화면을 벗어나면 5초 뒤에 타이머가 무효 처리됩니다. 계속하시겠습니까?'))return;setRemaining(minutes*60);setRunning(true);};
  return <div className="card p-7 md:p-10"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-blue-600">FOCUS TIMER</p><h2 className="mt-1 text-3xl font-bold">집중 시간 설정</h2></div><span className="rounded-full bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">30분당 {rewardPer30}P</span></div>
    <div className="mx-auto mt-10 max-w-xl text-center"><div className={`mx-auto grid h-64 w-64 place-items-center rounded-full border-[14px] ${running?'border-blue-600':'border-slate-100'} bg-white shadow-inner`}><div><p className="text-5xl font-bold tracking-tight">{running?fmt(remaining):`${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,'0')}`}</p><p className="mt-2 text-sm text-slate-400">{running?'남은 시간':'설정 시간'}</p></div></div>
      {!running&&<><input className="mt-10 w-full accent-blue-600" type="range" min="30" max="360" step="30" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><div className="mt-2 flex justify-between text-xs text-slate-400"><span>30분</span><span>6시간</span></div><p className="mt-5 text-sm">완료 시 <b className="text-blue-600">{(minutes/30*rewardPer30).toLocaleString()}P</b> 적립 예정</p></>}
      {hiddenLeft!==null&&<div className="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-600">앱으로 돌아오세요. {hiddenLeft}초 후 무효 처리됩니다.</div>}
      <div className="mt-7 flex gap-3">{running?<button className="btn w-full bg-rose-50 text-rose-600" onClick={()=>{if(confirm('중간에 취소하면 포인트가 적립되지 않습니다. 취소할까요?')){setRunning(false);setRemaining(0);}}}>타이머 취소</button>:<button className="btn-primary w-full" onClick={start}>타이머 시작</button>}</div>
    </div></div>
}
function Store({products,purchase,points}:any){return <div><div className="mb-5 flex items-end justify-between"><div><p className="text-sm font-semibold text-blue-600">SCHOOL STORE</p><h2 className="text-3xl font-bold">기프티콘 스토어</h2></div><b>{points.toLocaleString()}P</b></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.filter((p:Product)=>p.active).map((p:Product)=><div className="card overflow-hidden" key={p.id}><img src={p.image} alt={p.name} className="h-44 w-full object-cover"/><div className="p-5"><h3 className="font-bold">{p.name}</h3><p className="mt-1 text-sm font-semibold text-blue-600">{p.points.toLocaleString()}P</p><button className="btn-primary mt-5 w-full" onClick={()=>purchase(p)}>포인트로 구매</button></div></div>)}</div></div>}
function Wallet({wallet,setWallet}:any){ const active=wallet.filter((v:Voucher)=>!v.used); return <div><h2 className="mb-5 text-3xl font-bold">내 지갑</h2>{active.length===0?<div className="card p-12 text-center text-slate-400">보관 중인 기프티콘이 없습니다.</div>:<div className="grid gap-5 sm:grid-cols-2">{active.map((v:Voucher)=><VoucherCard key={v.id} voucher={v} onUse={()=>{}}/>)}</div>}</div>}
function VoucherCard({voucher}:any){ const [open,setOpen]=useState(false); const [token,setToken]=useState(uid()); const [left,setLeft]=useState(20); useEffect(()=>{if(!open)return;const t=setInterval(()=>setLeft(v=>{if(v<=1){setToken(uid());return 20;}return v-1;}),1000);return()=>clearInterval(t)},[open]); return <div className="card overflow-hidden"><div className="flex gap-4 p-5"><img src={voucher.image} className="h-20 w-20 rounded-2xl object-cover"/><div><h3 className="font-bold">{voucher.productName}</h3><p className="mt-1 text-xs text-slate-400">구매 {new Date(voucher.purchasedAt).toLocaleDateString()}</p><button className="btn-primary mt-3 py-2" onClick={()=>setOpen(true)}>매점에서 결제하기</button></div></div>{open&&<div className="border-t bg-slate-50 p-6 text-center"><PseudoQR value={token}/><p className="mt-3 text-sm font-bold">일회용 결제 코드</p><p className="mt-1 font-mono text-xs text-slate-500">{token.toUpperCase()}</p><p className="mt-2 text-xs text-blue-600">{left}초 후 자동 갱신</p></div>}</div>}
function PseudoQR({value}:{value:string}){ const cells=useMemo(()=>Array.from({length:144},(_,i)=>((value.charCodeAt(i%value.length)*17+i*13)%7)<3),[value]); return <div className="mx-auto grid h-44 w-44 grid-cols-12 bg-white p-2 shadow" >{cells.map((on,i)=><div key={i} className={on?'bg-slate-950':'bg-white'}/>)}</div> }
function Stats({growthTarget}:any){ const data=[35,55,0,90,120,60,150,80,110,140,95,180,120,150,130,165,200,145,160,190,130,210,175,220,150,180,240,200,230,250]; const growth=18; return <div className="space-y-5"><div className="card p-7"><div className="flex justify-between"><div><p className="text-sm text-slate-500">2026년 7월</p><h2 className="text-3xl font-bold">월간 성장 리포트</h2></div><span className="rounded-full bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-600">+{growth}%</span></div><div className="mt-8 flex h-56 items-end gap-1.5">{data.map((v,i)=><div key={i} className="flex-1 rounded-t-lg bg-blue-500/80" style={{height:`${Math.max(4,v/250*100)}%`}} title={`${i+1}일 ${v}분`}/>)}</div><div className="mt-2 flex justify-between text-xs text-slate-400"><span>1일</span><span>15일</span><span>30일</span></div></div><div className="card p-7"><p className="text-sm text-slate-500">성장률 보상</p><h3 className="mt-2 text-xl font-bold">목표 {growthTarget}% 이상 달성</h3><p className="mt-2 text-sm text-slate-500">현재 전월 대비 {growth}% 성장하여 특별 상품을 받을 수 있습니다.</p><button className="btn-primary mt-5" onClick={()=>alert('특별 보상 수령이 완료되었습니다!')}>특별 상품 받기</button></div></div>}

function AdminApp(props:any){ const nav:[AdminTab,string][]=[['overview','대시보드'],['products','상품 관리'],['scanner','바코드 스캔'],['settings','시스템 설정'],['schools','학교 관리'],['points','포인트 관리']]; return <div className="grid gap-5 md:grid-cols-[220px_1fr]"><aside className="card p-4"><p className="mb-4 px-3 text-xs font-bold text-slate-400">ADMIN CONSOLE</p><div className="flex gap-2 overflow-x-auto md:block md:space-y-2">{nav.map(([id,l])=><button key={id} onClick={()=>props.setTab(id)} className={`min-w-fit rounded-2xl px-4 py-3 text-left text-sm font-semibold md:w-full ${props.tab===id?'bg-slate-900 text-white':'text-slate-500 hover:bg-slate-100'}`}>{l}</button>)}</div></aside><section>{props.tab==='overview'&&<AdminOverview {...props}/>} {props.tab==='products'&&<ProductsAdmin {...props}/>} {props.tab==='scanner'&&<Scanner {...props}/>} {props.tab==='settings'&&<Settings {...props}/>} {props.tab==='schools'&&<Schools {...props}/>} {props.tab==='points'&&<Points {...props}/>}</section></div> }
function AdminOverview({students,products,wallet,rewardPer30}:any){return <div className="space-y-5"><div><p className="text-sm font-semibold text-blue-600">ADMIN DASHBOARD</p><h2 className="text-3xl font-bold">스테디 고등학교</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['등록 학생',students.length+'명'],['판매 상품',products.length+'개'],['발급 기프티콘',wallet.length+'개'],['기본 보상',rewardPer30+'P / 30분']].map(([a,b])=><div className="card p-5" key={a}><p className="text-sm text-slate-500">{a}</p><p className="mt-2 text-2xl font-bold">{b}</p></div>)}</div><div className="card p-6"><h3 className="font-bold">최근 운영 상태</h3><div className="mt-5 space-y-4 text-sm">{['타이머 보상 시스템 정상','일회용 결제 코드 갱신 정상','월간 성장률 계산 예약됨'].map(x=><div className="flex items-center justify-between" key={x}><span>{x}</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-600">정상</span></div>)}</div></div></div>}
function ProductsAdmin({products,setProducts}:any){ const empty={name:'',points:700,image:'',active:true}; const [form,setForm]=useState<any>(empty); const [edit,setEdit]=useState<string|null>(null); const file=(e:any)=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setForm({...form,image:r.result as string});r.readAsDataURL(f)}}; const save=()=>{if(!form.name||!form.image)return alert('상품명과 이미지를 입력해 주세요.');if(edit)setProducts((ps:Product[])=>ps.map(p=>p.id===edit?{...p,...form,points:Number(form.points)}:p));else setProducts((ps:Product[])=>[{id:uid(),...form,points:Number(form.points)},...ps]);setForm(empty);setEdit(null)}; return <div className="grid gap-5 lg:grid-cols-[380px_1fr]"><div className="card p-6"><h2 className="text-xl font-bold">{edit?'상품 수정':'상품 등록'}</h2><div className="mt-5 space-y-4"><div><label className="label">상품명</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label className="label">필요 포인트</label><input type="number" className="input" value={form.points} onChange={e=>setForm({...form,points:e.target.value})}/></div><div><label className="label">상품 이미지 업로드</label><input type="file" accept="image/*" className="input" onChange={file}/>{form.image&&<img src={form.image} className="mt-3 h-40 w-full rounded-2xl object-cover"/>}</div><button className="btn-primary w-full" onClick={save}>{edit?'수정 저장':'상품 등록'}</button></div></div><div className="space-y-3">{products.map((p:Product)=><div className="card flex items-center gap-4 p-4" key={p.id}><img src={p.image} className="h-20 w-20 rounded-2xl object-cover"/><div className="flex-1"><b>{p.name}</b><p className="text-sm text-blue-600">{p.points.toLocaleString()}P</p></div><button className="btn-soft" onClick={()=>{setEdit(p.id);setForm(p)}}>수정</button><button className="btn bg-rose-50 text-rose-600" onClick={()=>setProducts((ps:Product[])=>ps.filter(x=>x.id!==p.id))}>삭제</button></div>)}</div></div> }
function Scanner({wallet,setWallet}:any){ const [code,setCode]=useState(''); const redeem=()=>{const target=wallet.find((v:Voucher)=>!v.used);if(!target)return alert('사용 가능한 기프티콘이 없습니다.');setWallet((vs:Voucher[])=>vs.map(v=>v.id===target.id?{...v,used:true}:v));setCode('');alert(`${target.productName} 사용 완료 처리되었습니다.`)}; return <div className="card p-7"><p className="text-sm font-semibold text-blue-600">MOCK SCANNER</p><h2 className="mt-1 text-3xl font-bold">일회용 코드 확인</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><div className="grid min-h-72 place-items-center rounded-[28px] border-2 border-dashed border-slate-200 bg-slate-50 text-center"><div><div className="mx-auto h-36 w-36 rounded-3xl border-4 border-slate-300"/><p className="mt-4 text-sm text-slate-500">카메라 스캔 영역 (모의)</p></div></div><div className="flex flex-col justify-center"><label className="label">스캔된 일회용 코드</label><input className="input" placeholder="코드를 입력하거나 스캔하세요" value={code} onChange={e=>setCode(e.target.value)}/><button className="btn-primary mt-4" onClick={redeem}>기프티콘 사용 완료 처리</button><p className="mt-3 text-xs text-slate-400">프로토타입에서는 지갑의 첫 번째 미사용 기프티콘을 처리합니다.</p></div></div></div> }
function Settings({rewardPer30,setRewardPer30,growthTarget,setGrowthTarget,products,rewardProductId,setRewardProductId}:any){return <div className="card max-w-2xl p-7"><h2 className="text-3xl font-bold">학교 시스템 설정</h2><div className="mt-8 space-y-6"><div><label className="label">30분당 적립 포인트</label><div className="flex items-center gap-3"><input type="number" className="input" value={rewardPer30} onChange={e=>setRewardPer30(Number(e.target.value))}/><b className="whitespace-nowrap">P / 30분</b></div></div><div><label className="label">월간 성장률 보상 기준</label><div className="flex items-center gap-3"><input type="number" className="input" value={growthTarget} onChange={e=>setGrowthTarget(Number(e.target.value))}/><b>% 이상</b></div></div><div><label className="label">목표 달성 보상 상품</label><select className="input" value={rewardProductId} onChange={e=>setRewardProductId(e.target.value)}>{products.map((p:Product)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><div className="rounded-2xl bg-blue-50 p-4 text-sm text-blue-700">변경 사항은 즉시 학생 화면의 보상 계산과 성장 리포트에 반영됩니다.</div></div></div> }
function Schools({schools,setSchools}:any){const [name,setName]=useState('');const [code,setCode]=useState('');const add=()=>{if(!name||!code)return alert('학교 이름과 코드를 입력해 주세요.');setSchools((s:School[])=>[{id:uid(),name,code},...s]);setName('');setCode('')};return <div className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="card p-6"><h2 className="text-xl font-bold">새 학교 생성</h2><div className="mt-5 space-y-4"><div><label className="label">학교 이름</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div><label className="label">학교 코드</label><input className="input uppercase" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></div><button className="btn-primary w-full" onClick={add}>학교 생성</button></div></div><div className="space-y-3">{schools.map((s:School)=><div className="card flex items-center justify-between p-5" key={s.id}><div><b>{s.name}</b><p className="mt-1 font-mono text-xs text-slate-500">{s.code}</p></div><button className="btn bg-rose-50 text-rose-600" onClick={()=>setSchools((xs:School[])=>xs.filter(x=>x.id!==s.id))}>삭제</button></div>)}</div></div>}
function Points({students,setStudents}:any){const update=(id:string,val:number)=>setStudents((ss:Student[])=>ss.map(s=>s.id===id?{...s,points:val}:s));return <div><h2 className="mb-5 text-3xl font-bold">학생 포인트 관리</h2><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">학생</th><th>학년/반/번호</th><th>현재 포인트</th><th className="p-4">직접 수정</th></tr></thead><tbody>{students.map((s:Student)=><tr className="border-t" key={s.id}><td className="p-4 font-bold">{s.name}</td><td>{s.grade}학년 {s.classNo}반 {s.number}번</td><td className="font-semibold text-blue-600">{s.points.toLocaleString()}P</td><td className="p-4"><input type="number" className="input max-w-40" value={s.points} onChange={e=>update(s.id,Number(e.target.value))}/></td></tr>)}</tbody></table></div></div></div>}
